FROM docker:19.03 AS docker-cli

FROM python:3.9.1-slim-buster

RUN mkdir /work
# Because we need to specially handle bind mounts for sibling containers, set an environment flag here
ENV EXPEL_INSIDE_CONTAINER 1

# Copy over a prebuilt docker binary
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker

COPY expel.py /


ENTRYPOINT ["/expel.py"]
